version: '3.3'

services:
  backend:
    build:
      context: ./gettweet
    volumes:
      - ./gettweet:/gettweet
    restart: "no"
    ports:
      - "5000:5000"
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    env_file: .env
